env:
  CIRRUS_CLONE_DEPTH: 3

task:
  container:
    image: ubuntu:22.04
    cpu: 1
    memory: 512M
  env:
    DEBIAN_FRONTEND: noninteractive
  script:
    - apt-get -qy update >/dev/null
    - apt-get -qy install php7.4-cli >/dev/null # Same as on the live server.
    - ./test_ci.sh
