env:
  CIRRUS_CLONE_DEPTH: 3

task:
  container:
    image: ubuntu:20.04
    cpu: 1
    memory: 512M
  env:
    DEBIAN_FRONTEND: noninteractive
  script:
    - apt-get -qy update
    - apt-get -qy install php7.4-cli # Same as on the live server.
    - ./test_ci.sh
